### ISSUE TITLE
Fails when Bower is not globally installed.

### ISSUE THREAD

**Issue by rwjblue** [kategengler/ember-try#11]
This might seem obvious, but if the `bower` command is not available in `$PATH` we throw an error.

Ember CLI bundles `bower` itself (to avoid just this problem on `ember init` and `ember new`), so we should be able to tap into its `bower` install.

---

Discovered this due to ember-cli integration failures on Ember CLI's Windows CI system.  Example output:

```
     Running: node_modules\ember-cli\bin\ember try:testall
version: 0.2.2--af1623b89b
 
events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: spawn bower ENOENT
    at exports._errnoException (util.js:746:11)
    at Process.ChildProcess._handle.onexit (child_process.js:1053:32)
    at child_process.js:1144:20
    at process._tickCallback (node.js:355:11)
 ```

**Comment by rwjblue** [comment]
I'm toying with a potential solution for this now...
